name: Validate data

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install frictionless
      - name: Validate data files
        run: |
          set -euo pipefail
          shopt -s globstar nullglob 2>/dev/null || true
          files=(data/**/rates_normalized.csv)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No rates_normalized.csv files found" >&2
            exit 1
          fi
          for csv in "${files[@]}"; do
            echo "Validating ${csv}"
            frictionless validate "$csv" --schema schemas/rates_schema.json
          done
