name: Validate data

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install frictionless
      - name: Validate data files
        run: |
          shopt -s globstar 2>/dev/null || true
          frictionless validate data/**/rates_normalized.csv --schema schemas/rates_schema.json
